= A Zero-Dependency Mapping Library - API
:toc: macro

[.float-group]
--
[.left]
image::https://travis-ci.com/dmeiners88/mapping-api.svg?branch=master["Build Status", link="https://travis-ci.com/dmeiners88/mapping-api"]

[.left]
image::https://sonarcloud.io/api/project_badges/measure?project=de.dmeiners.mapping%3Amapping-api&metric=alert_status[link="https://sonarcloud.io/api/project_badges/measure?project=de.dmeiners.mapping%3Amapping-api&metric=alert_status"]

[.left]
image::https://api.bintray.com/packages/dmeiners/mapping/mapping-api/images/download.svg[link="https://bintray.com/dmeiners/mapping/mapping-api/_latestVersion"]
--

This is the API module of a simple library that enabled you to include scripting languages in a Java application.

toc::[]

== Features
* Zero dependencies
* Alternative to _Scripting for the Java Platform_ (https://jcp.org/en/jsr/detail?id=223[JSR-223])
* Different scripting language implementations
* Compile scripts inline, load from the classpath or roll your own `ScriptNameResolver`
* Extend your utility classes into the scripting language

== Limitations
* No handling of script engine/language mismatch
* Only one script engine implementation from the classpath is picked up

== Installation

=== Add the API Module
Add https://bintray.com/bintray/jcenter[JCenter] as a repository to your Maven POM:
[source,xml]
----
<repositories>
    <repository>
        <snapshots>
            <enabled>false</enabled>
        </snapshots>
        <id>jcenter</id>
        <name>JCenter</name>
        <url>https://jcenter.bintray.com</url>
    </repository>
</repositories>
----

Add the following dependency:
[source,xml]
----
<dependency>
include::pom.xml[tag=maven-coordinates]
</dependency>
----

IMPORTANT: Adding the Mapping API dependency alone will result in a no-op fallback implementation. See the next section for a list of implementation modules.

=== Add an Implementation Module
* https://github.com/dmeiners88/mapping-impl-jexl[Apache Commons JEXL]
* https://github.com/dmeiners88/mapping-impl-mvel[MVFLEX Expression Language]
* https://github.com/dmeiners88/mapping-impl-java[Java-on-Java]

== Usage

=== Simple Usage

[source,java,indent=0]
----
include::src/test/java/de/dmeiners/mapping/api/UsageTest.java[tag=simpleUsage]
----
<1> Create a new post processor
<2> Create a very simple target object
<3> Compile a simple script (scripting language dependent on the implementation available on the classpath, here it is Apache Commons JEXL)
<4> Execute the script, result type is guaranteed to the original type

=== Context Usage
[source,java,indent=0]
----
include::src/test/java/de/dmeiners/mapping/api/UsageTest.java[tag=contextUsage]
----
<1> Target object is a Map this time
<2> We create another map to use as script context
<3> Beware that the script text is dependent on the available implementation on the classpath, here it is Apache Commons JEXL

=== Expose Utility Class
[source,java,indent=0]
----
include::src/test/java/de/dmeiners/mapping/api/UsageTest.java[tag=exposeUtilityClass]
----
<1> We can register classes to expose static methods to the scripting language
<2> We can register objects to expose instance methods to the scripting language